PeteGoo/tcSlackBuildNotifier

- tcslackbuildnotifier-web-ui/src/main/resources/buildServerResources/SlackNotification/css/styles.css
- tcslackbuildnotifier-web-ui/src/main/resources/buildServerResources/SlackNotification/slackNotificationInclude.jsp
This is a simple suggestion how the scrolling of a long list of builds could be fixed with minimum changes.
> Fixed #28 - list of builds is scrollable now

- tcslackbuildnotifier-core/src/main/java/slacknotifications/teamcity/SlackNotificationListener.java
- tcslackbuildnotifier-core/src/main/java/slacknotifications/teamcity/settings/SlackNotificationConfig.java
- tcslackbuildnotifier-core/src/main/java/slacknotifications/teamcity/settings/SlackNotificationContentConfig.java
- tcslackbuildnotifier-core/src/main/java/slacknotifications/teamcity/settings/SlackNotificationMainConfig.java
- tcslackbuildnotifier-core/src/main/java/slacknotifications/teamcity/settings/SlackNotificationMainSettings.java
- tcslackbuildnotifier-core/src/main/java/slacknotifications/teamcity/settings/SlackNotificationProjectSettings.java
- tcslackbuildnotifier-core/src/test/java/slacknotifications/teamcity/settings/SlackNotificationConfigTest.java
- tcslackbuildnotifier-core/src/test/resources/project-settings-test-custom-content.xml
- tcslackbuildnotifier-web-ui/src/main/java/slacknotifications/teamcity/extension/SlackNotificationAjaxEditPageController.java
- tcslackbuildnotifier-web-ui/src/main/java/slacknotifications/teamcity/extension/SlackNotificationAjaxSettingsListPageController.java
- tcslackbuildnotifier-web-ui/src/main/java/slacknotifications/teamcity/extension/SlackNotificationIndexPageController.java
- tcslackbuildnotifier-web-ui/src/main/java/slacknotifications/teamcity/extension/SlackNotifierSettingsController.java
- tcslackbuildnotifier-web-ui/src/main/java/slacknotifications/teamcity/extension/bean/ProjectSlackNotificationsBean.java
- tcslackbuildnotifier-web-ui/src/main/java/slacknotifications/teamcity/extension/bean/SlacknotificationConfigAndBuildTypeListHolder.java
- tcslackbuildnotifier-web-ui/src/main/resources/buildServerResources/SlackNotification/index.jsp
- tcslackbuildnotifier-web-ui/src/main/resources/buildServerResources/SlackNotification/slackNotificationInclude.jsp
- tcslackbuildnotifier-web-ui/src/test/java/slacknotifications/teamcity/extension/bean/ProjectSlackNotificationsBeanTest.java
Currently if you want to change the content settings of the notification (show build agent, show commits / committers etc) then you have to change them globally.
This PR adds the ability to customise these settings per notification / build.
You can now customize:
- Show Elapsed Build Time
- Show Build Agent
- Show Commits
- Show Committers
- Max Commits to Display
- Bot Name
- Icon Url
> Add support for customizing content per notification

- tcslackbuildnotifier-core/src/main/java/slacknotifications/SlackNotificationImpl.java
This PR makes it so the committers string does not contain duplicates. As it stands now, you may see something like:
> Changes By
sdozor, sdozor, sdozor
This situation is made much worse when you have a lot of commits/committers - you end up with a committer string that is extremely long and kinda useless. With this change it should just look like this:
> Changes By
sdozor
> Avoid duplicate committer names

- tcslackbuildnotifier-core/src/main/java/slacknotifications/teamcity/TestListener.java
- tcslackbuildnotifier-core/src/main/java/slacknotifications/teamcity/payload/SlackNotificationPayloadManager.java
- tcslackbuildnotifier-core/src/main/java/slacknotifications/teamcity/payload/content/SlackNotificationPayloadContent.java
- tcslackbuildnotifier-core/src/main/java/slacknotifications/teamcity/settings/SlackNotificationMainConfig.java
squid:S1858 - “""toString()"" should never be called on a String object”. 
https://dev.eclipse.org/sonar/rules/show/squid:S1858
Fevzi Ozgul
> squid:S1858  "toString()" should never be called on a String object

- tcslackbuildnotifier-core/src/main/java/slacknotifications/teamcity/Loggers.java
- tcslackbuildnotifier-core/src/main/java/slacknotifications/teamcity/TeamCityIdResolver.java
- tcslackbuildnotifier-core/src/main/java/slacknotifications/teamcity/settings/converter/OldStyleBuildState.java
- tcslackbuildnotifier-core/src/main/java/slacknotifications/teamcity/settings/converter/SlackNotificationBuildStateConverter.java
- tcslackbuildnotifier-web-ui/src/main/java/slacknotifications/teamcity/extension/bean/ProjectSlackNotificationsBeanJsonSerialiser.java
squid:S1118 - “Utility classes should not have public constructors ”. 
https://dev.eclipse.org/sonar/rules/show/squid:S1118
Fevzi Ozgul
> Fixing squid:S1118 - Utility classes should not have public constructors.

- tcslackbuildnotifier-core/src/main/java/slacknotifications/teamcity/SlackNotificationListener.java
- tcslackbuildnotifier-web-ui/src/main/java/slacknotifications/teamcity/extension/SlackNotificationAjaxEditPageController.java
squid:S1854 - “ Dead stores should be removed ”. 
https://dev.eclipse.org/sonar/rules/show/squid:S1854
Fevzi Ozgul
> Fixing squid:S1854 Dead Stores should be removed

- tcslackbuildnotifier-core/src/main/java/slacknotifications/teamcity/payload/content/SlackNotificationPayloadContent.java
- tcslackbuildnotifier-core/src/main/java/slacknotifications/teamcity/settings/SlackNotificationConfig.java
- tcslackbuildnotifier-core/src/main/java/slacknotifications/teamcity/settings/SlackNotificationProjectSettings.java
- tcslackbuildnotifier-web-ui/src/main/java/slacknotifications/teamcity/extension/SlackNotificationIndexPageController.java
- tcslackbuildnotifier-web-ui/src/main/java/slacknotifications/teamcity/extension/bean/BuildSlacknotificationsBean.java
squid:S1155 - “Collection.isEmpty() should be used to test for emptiness”. 
https://dev.eclipse.org/sonar/rules/show/squid:S1155
Fevzi Ozgul
> Fixing squid:S1155 Collection.isEmpty() should be used to test for emptiness

- tcslackbuildnotifier-core/src/main/java/slacknotifications/SlackNotificationImpl.java
- tcslackbuildnotifier-core/src/main/java/slacknotifications/teamcity/SlackNotificationListener.java
- tcslackbuildnotifier-web-ui/src/main/java/slacknotifications/teamcity/extension/SlackNotificationAjaxEditPageController.java
squid:S1192 - “String literals should not be duplicated”. 
This PR will remove 150min of TD.
Fevzi Ozgul
> Fixing squid:S1192 String literals should not be duplicated part 1

- tcslackbuildnotifier-core/src/main/java/slacknotifications/teamcity/SlackNotificationListener.java
- tcslackbuildnotifier-web-ui/src/main/java/slacknotifications/teamcity/extension/bean/ProjectSlackNotificationsBean.java
- tcslackbuildnotifier-web-ui/src/main/java/slacknotifications/teamcity/extension/bean/SlacknotificationConfigAndBuildTypeListHolder.java
- tcslackbuildnotifier-web-ui/src/main/java/slacknotifications/teamcity/extension/bean/StateBean.java
This pull request is focused on resolving of occurrences of Squid :" class variable fields should not have public accessibility" . 
"Public class variable fields do not respect the encapsulation principle and has three main disadvantages:
Additional behavior such as validation cannot be added.
The internal representation is exposed, and cannot be changed afterwards.
Member values are subject to change from anywhere in the code and may not meet the programmer's assumptions.
By using private attributes and accessor methods (set and get), unauthorized modifications are prevented."
Fevzi Ozgul
> Fixing squid:ClassVariableVisibilityCheck  Class variable fields should not have public accessibility

- tcslackbuildnotifier-core/src/main/java/slacknotifications/teamcity/payload/SlackNotificationPayloadManager.java
- tcslackbuildnotifier-core/src/main/java/slacknotifications/teamcity/payload/util/SlackNotificationBeanUtilsVariableResolver.java
- tcslackbuildnotifier-core/src/main/java/slacknotifications/teamcity/settings/SlackNotificationProjectSettings.java
- tcslackbuildnotifier-web-ui/src/main/java/slacknotifications/teamcity/extension/SlackNotificationAjaxSettingsListPageController.java
- tcslackbuildnotifier-web-ui/src/main/java/slacknotifications/teamcity/extension/SlackNotificationBuildTabExtension.java
- tcslackbuildnotifier-web-ui/src/main/java/slacknotifications/teamcity/extension/SlackNotificationIndexPageController.java
squid:S1192 - “String literals should not be duplicated”. 
This PR will reduce 120 min TD.
Fevzi Ozgul
> Fixing squid: S1192 String literals should not be duplicated part 2

- tcslackbuildnotifier-core/src/main/java/slacknotifications/teamcity/settings/SlackNotificationConfig.java
squid:S1192 - “String literals should not be duplicated”. 
TD removal : 190 min
Fevzi Ozgul
> Fixing squid: S1192 String literals should not be duplicated part 3

- tcslackbuildnotifier-core/src/main/java/slacknotifications/SlackNotificationCollection.java
squid:S1132- “Strings literals should be placed on the left side when checking for equality”. 
This PR will remove 110 min of TD.
Fevzi Ozgul
> Fixing squid: S1132 String literals should be placed on the left side when checking equality part 1

- tcslackbuildnotifier-core/src/main/java/slacknotifications/SlackNotificationImpl.java
- tcslackbuildnotifier-core/src/main/java/slacknotifications/teamcity/settings/SlackNotificationMainConfig.java
squid:S1132- “Strings literals should be placed on the left side when checking for equality”. 
This PR will remove 30 min of TD.
Fevzi Ozgul
> Fixing squid: S1132 String literals should be placed on the left when checking equality part 2

- tcslackbuildnotifier-web-ui/src/main/java/slacknotifications/teamcity/extension/SlackNotificationAjaxEditPageController.java
squid:S1132- “Strings literals should be placed on the left side when checking for equality”
This PR will remove 90 min of TD.. 
Fevzi Ozgul
> Fixing squid: S1132 String literals should be placed on the left when checking for equality part 3

- tcslackbuildnotifier-web-ui/src/main/java/slacknotifications/teamcity/extension/SlackNotificationAjaxEditPageController.java
squid:S1132- “Strings literals should be placed on the left side when checking for equality”. 
This PR will remove 110 min of TD.
Fevzi Ozgul
> Fixing squid: S1132 String literals should be placed on the left when checking for equality part 4 final

- tcslackbuildnotifier-core/src/main/java/slacknotifications/teamcity/settings/SlackNotificationMainConfig.java
squid:S1192 - “String literals should not be duplicated”. 
This PR will reduce 132min of TD.
Fevzi Ozgul
> Fixing squid: S1192 String literals should not be duplicated PR#99 replacement

- tcslackbuildnotifier-core/src/main/java/slacknotifications/teamcity/BuildState.java
squid:S135 - “Loops should not contain more than a single "break" or "continue" statement”. 
This PR will remove 80 min of TD.
https://dev.eclipse.org/sonar/rules/show/squid:S135
Fevzi Ozgul
> Fixing squid: S135 Loops should not contain more than a single "break  " or "continue" statement part 2

- tcslackbuildnotifier-core/src/main/java/slacknotifications/teamcity/BuildState.java
squid:S135 - “Loops should not contain more than a single "break" or "continue" statement”. 
This PR will remove 40 min of TD.
https://dev.eclipse.org/sonar/rules/show/squid:S135
Fevzi Ozgul
> Fixing squid:S135 Loops should not contain more than a single "break" or "continue" statement

- tcslackbuildnotifier-web-ui/src/main/java/slacknotifications/teamcity/extension/SlackNotificationAjaxEditPageController.java
squid:S1132- “Strings literals should be placed on the left side when checking for equality”. 
This PR will remove 30 min of TD.
Fevzi Ozgul
> Fixing squid: S1132 Strings literals should be placed on the left side when checking for equality

- tcslackbuildnotifier-core/src/main/java/slacknotifications/teamcity/settings/SlackNotificationMainConfig.java
squid:S1192 - “String literals should not be duplicated”.
This PR will  remove 62 min of TD. 
Fevzi Ozgul
> Release/string literals should not be duplicated final- replaces PR#98

- tcslackbuildnotifier-core/src/main/java/slacknotifications/teamcity/settings/converter/OldStyleBuildState.java
common-java: DuplicatedBlocks - “Source files should not have any duplicated blocks”. 
This PR will remove 30 min of TD.
https://dev.eclipse.org/sonar/rules/show/common-java:DuplicatedBlocks
Fevzi Ozgul
> Fixing common-java:DuplicatedBlocks Source files should not have any duplicated blocks part 3

- tcslackbuildnotifier-core/src/main/java/slacknotifications/teamcity/SlackNotificationListener.java
- tcslackbuildnotifier-core/src/main/java/slacknotifications/teamcity/settings/SlackNotificationMainSettings.java
- tcslackbuildnotifier-core/src/main/java/slacknotifications/teamcity/settings/SlackNotificationProjectSettings.java
- tcslackbuildnotifier-core/src/main/java/slacknotifications/teamcity/settings/SlackNotificationProjectSettingsFactory.java
- tcslackbuildnotifier-web-ui/src/main/java/slacknotifications/teamcity/extension/SlackNotificationAjaxEditPageController.java
- tcslackbuildnotifier-web-ui/src/main/java/slacknotifications/teamcity/extension/SlackNotificationAjaxSettingsListPageController.java
- tcslackbuildnotifier-web-ui/src/main/java/slacknotifications/teamcity/extension/SlackNotificationBuildTabExtension.java
- tcslackbuildnotifier-web-ui/src/main/java/slacknotifications/teamcity/extension/SlackNotificationIndexPageController.java
- tcslackbuildnotifier-web-ui/src/main/java/slacknotifications/teamcity/extension/SlackNotificationProjectTabExtension.java
squid:S1161- “  "@Override" annotation should be used on any method overriding (since Java 5) or implementing (since Java 6) another one”. 
This PR will remove 70 min of TD.
You can find more information about the issues here: 
https://dev.eclipse.org/sonar/rules/show/squid:S1161
Fevzi Ozgul
> Fixing squid. S1161 "@Override" annotation should be used on any method overriding (since Java 5) or implementing (since Java 6) another one

- tcslackbuildnotifier-core/src/main/java/slacknotifications/teamcity/settings/SlackNotificationConfig.java
- tcslackbuildnotifier-core/src/test/java/slacknotifications/teamcity/settings/SlackNotificationConfigTest.java
- tcslackbuildnotifier-core/src/test/resources/project-settings-test-all-but-respchange-states-enabled.xml
- tcslackbuildnotifier-core/src/test/resources/project-settings-test-all-states-disabled.xml
- tcslackbuildnotifier-core/src/test/resources/project-settings-test-all-states-enabled-with-branch-and-custom-templates.xml
- tcslackbuildnotifier-core/src/test/resources/project-settings-test-all-states-enabled-with-custom-templates.xml
- tcslackbuildnotifier-core/src/test/resources/project-settings-test-all-states-enabled-with-specific-builds.xml
- tcslackbuildnotifier-core/src/test/resources/project-settings-test-all-states-enabled.xml
- tcslackbuildnotifier-core/src/test/resources/project-settings-test-custom-content.xml
- tcslackbuildnotifier-core/src/test/resources/project-settings-test-slacknotifications-disabled.xml
- tcslackbuildnotifier-core/src/test/resources/testdoc1.xml
For backwards-compatibility, allows configs to be read/written without a token set. Includes test updates as well.
This reverts commit 4b8cb6284b5bc1d9a784601af64499e5b3b9c6b1.
> Set API token in SlackNotificationConfig#getAsElement, fixes #86

- tcslackbuildnotifier-core/src/main/java/slacknotifications/teamcity/TeamCityIdResolver.java
squid:S1166- “ Exception handlers should preserve the original exception”. 
This PR will remove 110 min of TD.
You can find more information about the issues here: 
https://dev.eclipse.org/sonar/rules/show/squid:S1166
Fevzi Ozgul
> Fixing squid: S1166 Exception handlers should preserve the original exception

- tcslackbuildnotifier-core/src/main/java/slacknotifications/SlackNotificationImpl.java
To enable slack notification for the commit user, the format of the user should be like <@username> instead of just @username
> Update slackUser format to enable mention in slack

- README.md
As #144 and #138 shows, there is some confusion on where the actual tab is located. Some try to look at the Project and Build configuration setting pages that live under the main Administration category, which is wrong.
This tries to help minimize the confusion.
> Remove confusion on where the Slack tab lives

- tcslackbuildnotifier-core/src/main/java/slacknotifications/SlackNotificationImpl.java
So `username` & `icon_url` are not ignored
According to [Slack API docs](https://api.slack.com/methods/chat.postMessage):
* `icon_url` : URL to an image to use as the icon for this message. Must be used in conjunction with `as_user` set to `false`, ___otherwise ignored___
* `username`: Set your bot's user name. Must be used in conjunction with `as_user` set to `false`, ___otherwise ignored___
> Set `as_user` to false

- tcslackbuildnotifier-core/src/main/java/slacknotifications/SlackNotification.java
- tcslackbuildnotifier-core/src/main/java/slacknotifications/SlackNotificationImpl.java
- tcslackbuildnotifier-core/src/main/java/slacknotifications/teamcity/SlackNotificationListener.java
- tcslackbuildnotifier-core/src/main/java/slacknotifications/teamcity/SlackNotificator.java
- tcslackbuildnotifier-core/src/main/java/slacknotifications/teamcity/payload/content/Commit.java
- tcslackbuildnotifier-core/src/main/java/slacknotifications/teamcity/payload/content/PayloadContentCommits.java
- tcslackbuildnotifier-core/src/main/java/slacknotifications/teamcity/payload/content/SlackNotificationPayloadContent.java
- tcslackbuildnotifier-core/src/main/java/slacknotifications/teamcity/settings/SlackNotificationConfig.java
- tcslackbuildnotifier-core/src/main/java/slacknotifications/teamcity/settings/SlackNotificationProjectSettings.java
- tcslackbuildnotifier-core/src/test/java/slacknotifications/teamcity/SlackNotificationListenerTest.java
- tcslackbuildnotifier-web-ui/src/main/java/slacknotifications/teamcity/extension/SlackNotificationAjaxEditPageController.java
- tcslackbuildnotifier-web-ui/src/main/java/slacknotifications/teamcity/extension/bean/ProjectSlackNotificationsBean.java
- tcslackbuildnotifier-web-ui/src/main/java/slacknotifications/teamcity/extension/bean/SlacknotificationConfigAndBuildTypeListHolder.java
- tcslackbuildnotifier-web-ui/src/main/resources/buildServerResources/SlackNotification/index.jsp
- tcslackbuildnotifier-web-ui/src/main/resources/buildServerResources/SlackNotification/slackNotificationInclude.jsp
Introduce "Mention who triggered" feature and related setting. Now you can enable "Mention who triggered" option in Slack project config to add a mention of the person who triggered the build.
Also slack username was replaced with userid as currently Slack requires to use userid instead of just username for mentioning.
Should cover needed functionality for #147
> Mention who triggered
